/* Database schema to keep the structure of entire database. */
CREATE DATABASE vet_clinic;

CREATE TABLE animals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name VARCHAR, 
    date_of_birth date, 
    escape_attempts INT, 
    neutered BOOLEAN, 
    weight_kg DECIMAL
);
